name: Raid Reminder

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Call raid reminder API
        run: |
          curl -L -X GET "https://lostark-mark-001.vercel.app/api/raid-reminder"
